/// Sales measures
table Sales

	/// Sales amount broken down by payment due date.
	measure 'Amount by Due Date' =
			CALCULATE(
			  SUM(Sales[Amount])
			, USERELATIONSHIP(
			    Sales[Due Date]
			  ,'Date'[Date]
			  )
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average cost per item' = DIVIDE(SUM('Sales'[Amount]), SUM('Sales'[Number of Items]))
		lineageTag: 4575000f-7123-4b8d-b8c3-e8ed65c79200

	column Amount
		dataType: double
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: CustomerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Due Date'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: Due Date

		annotation SummarizationSetBy = Automatic

	column 'Number of Items'
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Number of Items

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: ProductID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price Discount'
		dataType: double
		isHidden
		formatString: 0.0%;-0.0%;0.0%
		summarizeBy: none
		sourceColumn: Unit Price Discount

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Sales-e07b8a6f-bcc3-4a1e-b157-f8f3b98a9e1b = m
		mode: import
		source =
				let
				    Source = Sql.Database("sql-powerbiprodev.database.windows.net", "AdventureWorks", [Query="SELECT#(lf)  d.[SalesOrderID]#(lf), h.CustomerID#(lf), d.[ProductID]#(lf), d.[OrderQty]#(lf), d.[UnitPrice]#(lf), d.[UnitPriceDiscount]#(lf), d.[LineTotal]#(lf), h.OrderDate#(lf), h.ShipDate#(lf), h.DueDate#(lf), IIF(h.OnlineOrderFlag = 1, 'Online', 'In store') AS Channel#(lf)FROM [SalesLT].[SalesOrderDetail] d#(lf)  INNER JOIN SalesLT.SalesOrderHeader h ON h.SalesOrderID = d.SalesOrderID"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"SalesOrderID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"LineTotal", "Amount"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"ShipDate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"DueDate", "Due Date"}, {"OrderDate", "Order Date"}, {"OrderQty", "Number of Items"}, {"UnitPrice", "Unit Price"}, {"UnitPriceDiscount", "Unit Price Discount"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

