trigger:
  branches:
    include:
      - rc/*
      - main
  paths:
    include:
      - /powerbi-pro-devex-series/04-MultipleReports/reports/SalesKPI
pr:
  branches:
    include:
      - rc/*
  paths:
    include:
      - /powerbi-pro-devex-series/04-MultipleReports/reports/SalesKPI

stages:
- template: ../../tools/report-pipeline-stages.yaml
  parameters:
    reportFolder: /powerbi-pro-devex-series/04-MultipleReports/reports/SalesKPI
