trigger:
  branches:
    include:
      - rc/*
      - main
  paths:
    include:
      - /powerbi-pro-devex-series/05-DatasetEnvironments/reports/CustomerOverview
pr:
  branches:
    include:
      - rc/*
  paths:
    include:
      - /powerbi-pro-devex-series/05-DatasetEnvironments/reports/CustomerOverview

stages:
- template: ../../tools/report-pipeline-stages.yaml
  parameters:
    reportFolder: /powerbi-pro-devex-series/05-DatasetEnvironments/reports/CustomerOverview
